config/routes.rb
HtmlPdf::Application.routes.draw do

  root :to => "workbooks#index"
  

  resources :workbooks do 
  	post :choose
  end

end

app/models/url.rb
class Url < ActiveRecord::Base
  attr_accessible :url, :workbook_id, :use
  belongs_to :workbook
end

app/models/workbook.rb
class Workbook < ActiveRecord::Base
  attr_accessible :string, :title
  attr_accessible :string, :bookmark_file
  attr_accessible :bookmark
  has_attached_file :bookmark
  has_attached_file :pdf

  
  has_many :urls
  accepts_nested_attributes_for :urls 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/test.rb
#! /usr/local/bin/ruby 
# encoding: utf-8 
require 'rubygems'
require 'uri'


# Set up gems listed in the Gemfile.
ENV['BUNDLE_GEMFILE'] ||= File.expand_path('../../Gemfile', __FILE__)

require 'bundler/setup' if File.exists?(ENV['BUNDLE_GEMFILE'])

bookmark_file = File.new("bookmarks_6_7_12.html", "r", :encoding => "BINARY")

contents = bookmark_file.read
# extract first URI from html_string
#url_array = URI.extract(content)
url_array = contents.scan(/\bhttps?:\/\/\S+\b/)
puts url_array

app/controllers/urls_controller.rb
class UrlsController < ApplicationController
  def index
  end

  def show
  end


  # GET /jobs/new
  # GET /jobs/new.json
  def new
    @url = Url.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @url }
    end
  end

  # GET /jobs/1/edit
  def edit
    @url = Url.find(params[:id])
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @url = Url.new(params[:workbook])
    
    respond_to do |format|
      if @url.save
        format.html { redirect_to @url, :notice => 'Url was successfully created.' }
        format.json { render :json => @url, :status => :created, :location => @url }
      else
        format.html { render :action => "new" }
        format.json { render :json => @url.errors, :status => :unprocessable_entity }
      end
    end
  end

  def update
  end

  def delete
  end
end

app/controllers/workbooks_controller.rb
# encoding: utf-8
class WorkbooksController < ApplicationController

require 'fileutils'
require "pdf/merger"

PDF_ROOT = "temp_pdf"

  def parse_bookmark_file(filepath)
  	bookmark_file = File.new(filepath, "rb", :encoding => "BINARY")
  	contents = bookmark_file.read
  	url_array = contents.scan(/\bhttps?:\/\/\S+\b/)
  	return url_array 
  end
  
  def make_pdf(id, list_of_URL_ids)
	@workbook = Workbook.find(id)
	if !File.directory? "#{PDF_ROOT}"
        Dir.mkdir("#{PDF_ROOT}") #make root dir if it doesn't exist?
    end
    if !File.directory? "#{PDF_ROOT}/#{id}/"
    	Dir.mkdir("#{PDF_ROOT}/#{id}/")
    end
	list_of_URL_ids.each do |url_id|
	     @cur_url = @workbook.urls.find(url_id)
	     kit = PDFKit.new(@cur_url.url, :print_media_type => true)
	     file = kit.to_file("#{PDF_ROOT}/#{id}/#{url_id}.pdf")
    end
    
    files_list = Dir.glob("#{PDF_ROOT}/#{id}/*.pdf")
    pdf = PDF::Merger.new
    for file in files_list
      puts file
      pdf.add_file file
    end
    pdf.save_as "#{PDF_ROOT}/#{id}/out.pdf"
    @workbook.pdf = File.open("#{PDF_ROOT}/#{id}/out.pdf")
    @workbook.save!
    FileUtils.rm_rf "#{PDF_ROOT}/#{id}/"
    #send_file @workbook.pdf.path, :type=> 'application/pdf'
  end  
  
  def index
	@workbooks = Workbook.all
	respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @workbooks }
    end
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
    @workbook = Workbook.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @workbook }
    end
  end

  # GET /jobs/new
  # GET /jobs/new.json
  def new
    @workbook = Workbook.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @workbook }
    end
  end

  # GET /workbooks/1/edit
  def edit
    @workbook = Workbook.find(params[:id])
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @workbook = Workbook.new(params[:workbook])
    
    respond_to do |format|
      if @workbook.save
      	url_array = parse_bookmark_file(@workbook.bookmark.path)
      	url_array.each do |url|
	    @workbook.urls.build(:url => url, :use => false)
	    @workbook.save
	  end
        format.html { redirect_to @workbook, :notice => 'Workbook was successfully created.' }
        format.json { render :json => @workbook, :status => :created, :location => @workbook }

      else
        format.html { render :action => "new" }
        format.json { render :json => @workbook.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /jobs/1
  # PUT /jobs/1.json
  def update
    @workbook = Workbook.find(params[:id])   

    respond_to do |format|
      if @workbook.update_attributes(params[:job])

        format.html { redirect_to @workbook, :notice => 'Workbook was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @workbook.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @workbook = Workbook.find(params[:id])
    @workbook.destroy

    respond_to do |format|
      format.html { redirect_to jobs_url }
      format.json { head :ok }
    end
  end
  
  def choose
  	Url.update_all(:use => false)
  	@workbook = Workbook.find(params[:workbook_id])
  	Url.update_all({:use => true}, :id => params[:url_ids])
  	make_pdf(@workbook.id, params[:url_ids])
  	
  	redirect_to :action => "show", :id => @workbook.id
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/urls_helper.rb
module UrlsHelper
end

app/helpers/workbook_helper.rb
module WorkbookHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HtmlPdf</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/urls/create.html.erb
<h1>Urls#create</h1>
<p>Find me in app/views/urls/create.html.erb</p>

app/views/urls/delete.html.erb
<h1>Urls#delete</h1>
<p>Find me in app/views/urls/delete.html.erb</p>

app/views/urls/index.html.erb
<h1>Urls#index</h1>
<p>Find me in app/views/urls/index.html.erb</p>

app/views/urls/show.html.erb
<h1>Urls#show</h1>
<p>Find me in app/views/urls/show.html.erb</p>

app/views/urls/update.html.erb
<h1>Urls#update</h1>
<p>Find me in app/views/urls/update.html.erb</p>

app/views/workbooks/_form.html.erb
<%= form_for @workbook, :html => { :multipart => true } do |f| %>


  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>

  <div>
    <%= f.label :bookmark %><br />
   <%= f.file_field :bookmark %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
  
<% end %>

app/views/workbooks/create.html.erb
<h1>Workbook#create</h1>
<p>Find me in app/views/workbook/create.html.erb</p>

app/views/workbooks/delete.html.erb
<h1>Workbook#delete</h1>
<p>Find me in app/views/workbook/delete.html.erb</p>

app/views/workbooks/edit.html.erb
<h1>Edit Workbook</h1>

<%= render 'form' %>

	

<%= link_to 'Back', workbooks_path %>

app/views/workbooks/index.html.erb
<% @workbooks.each do |workbook| %>
<div>
<p><%= workbook.title %></p>

<%= link_to 'bookmark file', workbook.bookmark.url  %>

</p>
<p>
<%= link_to 'pdf file', workbook.pdf.url(:original, false)  %>

</p>
</div>
</p>------</p>
<% end %>

app/views/workbooks/new.html.erb
<h1>New Workbook</h1>

<%= render 'form' %>

<%= link_to 'Back', workbooks_path %>

app/views/workbooks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
    <%= @workbook.title %>
</p>
<p>
<%= link_to 'bookmark file', @workbook.bookmark.url  %>

</p>


<%= form_tag({:action => "choose", :controller => "workbooks", :workbook_id => @workbook.id}, :html => {:multipart => true }) do |f| %>
 	<ul>
 	<% @workbook.urls.each do |u| %>
    <li>
      <%= check_box_tag "url_ids[]", u.id, (u.use ?  true : false ) %>
      <%= u.url %>
      <% if u.use?%>
      	<strong>use</strong>
      <% end %>	
    </li>
  <% end %>
 </ul>
  <%= submit_tag "Create PDF" %>
<% end %>
<% if @workbook.pdf? %>
    <p>
    <%= link_to 'pdf file', @workbook.pdf.url(:original, false), :target => "_blank"  %>
    </p>
<% end %>



<%= link_to 'Back', workbooks_path %>